config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: %i[new create destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(', ').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: 'should match confirmation', if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  include ArticlesHelper
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Your article '#{@article.title}' has been created!"
    redirect_to article_path(@article)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article_id
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' updated!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Goodbye, '#{@article.title}', you have been deleted."

    redirect_to articles_path
  end
end

app/controllers/author_sessions_controller.rb
# frozen_string_literal: true

class AuthorSessionsController < ApplicationController
  def new; end

  def create
    if login(params[:email], params[:password])
      flash.notice = 'Logged in successfully'
      redirect_back_or_to articles_path
    else
      flash.notice = 'Login failed.'
      render action: :new
    end
  end

  def destroy
    logout
    flash.notice = 'Logged out!'
    redirect_to articles_path
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit update destroy]
  before_action :zero_authors_or_authenticated, only: %i[new create]
  before_action :require_login, except: %i[new create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show; end

  def zero_authors_or_authenticated
    unless Author.count.zero? || current_user
      redirect_to root_path
      false
    end
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit; end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :require_login, except: [:create]
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :require_login, only: [:destroy]
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later.</p>
  <p class="comment"><%= comment.body%></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>

  <li>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
    <span>Be memorable!</span>
  </li>

  <li>
    <%= f.label :body %><br>
    <%= f.text_area :body%><br>
    <span>Be legendary!</span>
  </li>

  <li>
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %><br>
    <span>Main topics over here.</span>
  </li>

  <li>
    <%= f.submit %>
  </li>
  </ul>
<% end %>

app/views/articles/edit.html.erb
<div class="top-embody">
  <h1>Edit Article</h1>
</div>

<div class="session">
  <%= render partial: 'form' %>
</div>

app/views/articles/index.html.erb
<div class="top-embody">
  <h1>All Articles</h1>
</div>

<div class="articles">
  <% @articles.each do |article| %>
    <div class="article">
      <%= link_to article.title, article_path(article) %>
    </div>
  <% end %>
</div>

<div class="backopt">
  <% if logged_in? %>
    <%= link_to "Create a New Article", new_article_path, class: 'new_article' %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="top-embody">
  <h1>Create a New Article</h1>
</div>

<div class="session">
  <%= render partial: 'form' %>
</div>

app/views/articles/show.html.erb
<div class="top-embody">
  <h1><%= @article.title %></h1>
  <p>Tags:
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>
</div>

<div class="article">
  <p><%= @article.body %></p>
</div>

<div class="backopt">
  <% if logged_in? %>
  <div class="article-options">
    <%= link_to "Edit Article", edit_article_path(@article) %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"} %><br>
  </div>
  <% end %>
</div>

<div class="comments">
  <h3>Comments (<%= @article.comments.size %>)</h3>
    <%= render partial: 'articles/comment', collection: @article.comments %>
    <%= render partial: 'comments/form' %>
</div>

app/views/author_sessions/new.html.erb
<div class="top-embody"><h1>Login</h1></div>

<div class="session">
<%= form_tag author_sessions_path, method: :post do %>
  <ul>
  <li>
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
    <br>
  </li>
  <li>
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
    <br>
  </li>
  <li>
    <%= submit_tag "Login" %>
  </li>
<% end %>
</ul>
</div>

<div class="backopt">
<%= link_to 'Back', articles_path %>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="top-embody">
  <h1>Editing Author</h1>
</div>

<%= render 'form', author: @author %>

<div class="backopt">
  <%= link_to 'Show', @author %>
  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<div class="top-embody">
  <h1>New Author</h1>
</div>

<%= render 'form', author: @author %>

<div class="backopt">
  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="article">
  <p>
    <strong>Username:</strong>
    <%= @author.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @author.email %>
  </p>
</div>

<div class="backopt">
  <%= link_to 'Edit', edit_author_path(@author) %> |
  <%= link_to 'Back', authors_path %>
</div>

app/views/comments/_form.html.erb
<h3>Leave your Mark:</h3>

<%= form_for [@article, @comment] do |f| %>
<p>
  <%= f.label :author_name, "Your Name" %><br>
  <%= f.text_field :author_name %>
</p>
<p>
  <%= f.label :author_email, "Your e-mail" %><br>
  <%= f.text_field :author_email %>
</p>
<p>
  <%= f.label :body, "Your Comment (be nice, we're humans too)" %><br>
  <%= f.text_field :body %>
</p>
<p>
  <%= f.submit 'Submit' %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Me Out~</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', 'reset-form', 'forms', 'colors', 'fonts', 'top-navbar', 'reset', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Sans+Pro&display=swap" rel="stylesheet">

  </head>

  <body>
  <div class="top-navbar">
    <h1 class="title">Blog Me Out~</h1>
    <div class="flash"><p><%= flash.notice %></p></div>
    <div class="login">
      <% if logged_in? %>
        <%= "Logged in as #{current_user.username}" %>
        <%= link_to "(logout)", logout_path %>
      <% else %>
        <%= link_to "(login)", login_path %>
      <% end %>
    </div>
    <div class="navtags"><%= link_to "Tags", tags_path %></div>
    <div class="main"><%= link_to "Articles", articles_path %></div>
  </div>
  
  <div class="embody">
    <%= yield %>
  </div>

  <div class="footer">
    <p>Made by <a href="https://twitter.com/miss_sizigia">Faustina</a> with 💖 and <a href="https://en.wikipedia.org/wiki/Mate_(drink)">mate</a>.</p>
  </div>
  </body>
</html>

app/views/tags/index.html.erb
<div class="top-embody">
<h1>All Tags</h1>
</div>

<div class="tags">
  <% @tags.each do |tag| %>
    <div class="tag">
      <%= link_to tag.name, tag_path(tag) %>
      <% if logged_in?%>
        <%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: "Are you sure you want to delete the tag?"} %><br>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tags/show.html.erb
<div class="top-embody">
<h1>Articles Tagged with <%= tag.name %></h1>
</div>

<div class="tags">
<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
</div>